project:
  type: book
  output-dir: tempdocs

book:
  title: "Learning is messy, performance is beautiful"
  author: "Laura Pankratz and Elizabeth Pankratz"
  date: today

  page-footer:
    left: |
      This book is by Laura Pankratz and Elizabeth Pankratz.
    right: |
      This book is built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    
    - part: "What is learning?"
      chapters:
      - part1/intro-learning.qmd
      - part1/learning-taxonomies.qmd
    
    - part: "The cognitive process of learning, and how to facilitate it"
      chapters:
      - part2/learning-is-messy.qmd
      - part2/learning-takes-energy.qmd
      - part2/learning-by-doing.qmd
      - part2/interact-w-students.qmd
      - part2/designing-course.qmd
      
    - part: "The behavioural outcomes of learning, and how to assess them"
      chapters:
      - part3/more-than-grades.qmd
      - part3/designing-assessment.qmd
      - part3/designing-question.qmd
      - part3/designing-mcq.qmd
      - part3/designing-sgr.qmd
      - part3/formative.qmd
      - part3/summative.qmd
      
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: united
    author-meta: "Laura Pankratz and Elizabeth Pankratz"
