# Conclusion  {.unnumbered}

In one of our first "business meetings" about this little book, I (Elizabeth) asked Laura to think about a title.
A title is a big decision, and I expected the deliberation to take a while.
But within seconds, Laura said, "What about something like ... 'Learning is messy, performance is beautiful'?"
How succinctly that parallel summed up everything we'd been discussing!

**Learning is messy.**
A foundation of Laura's philosophy.
Foundations are shaky, ideas are misunderstood—and that is all part of the process.
Within the mess, an excellent teacher can always find something good, something worth building on.
And what's not worth building on is not a "mistake", but a pointer toward some misunderstanding that an excellent teacher can help improve.

I've embraced this idea wholeheartedly too.
But for the second part of the title, I did put my own stink on things.
I don't view performance as especially beautiful.
Performance is what our modern educational systems force students to do, so that we can (inaccurately) summarise their achievement (not their learning) with a single number (which employers tend not to even care about as much as educators think they do).
"Beautiful" is too nice a word for so uncaring a thing.

But **performance *is* polished.**
Speaking as somebody who was a student herself not too long ago: students are very practiced at playing the game of grades.
It's easier to pass an exam by stuffing one's short-term memory full of facts than by engaging in the messy work of genuine, long-term, sustained learning—so that's what students do, myself absolutely included.
This behaviour is essentially self-preservation, and it's emerged because along the way, educators' well-intentioned goal of understanding what students have learned has mutated into an ungenerous demand for a polished song-and-dance.

But students adapt to how we assess.
And if we assess fairly and with a focus on real learning (not to mention on students' well-being), for example with more thoughtful assessment design, emphasis on formative assessment, and even adoption of alternative assessment methods [@SambellEtAl2012; @Blum2020; @ClarkTalbert2023], then I do think that would be a beautiful thing.

<br>

---

<br>

For my whole life, I've looked up to Laura as a teacher.
She helped me through many classes I wasn't sure I'd pass.
Now, a teacher myself, I'm really happy to have had this chance to collect and share her wisdom and experience.
We both hope that you, reader, will gain something from it that will help you guide your students through the messy process of learning.
