# Designing a course {#sec-designing-course}

## Know the purpose

In [Section @sec-interact-w-students], we advised you to know the purpose of every question you ask.
The same principle holds at the level of course design: know the purpose of every piece of material you include.

Intentionally curating what goes into your course—and then telling students why you included each concept—will help motivate students to learn the material for reasons beyond "I need this for the test".


## Break down silos

Courses tend to be organised into units.
Each unit gets its own box, and the material in that box is tidily compartmentalised away from the material in other boxes.
When each unit is finished, that box is closed up, and students and teacher move on to the next one.
Laura calls this practice "siloing".

Siloing is a common way to organise a course, but it's not a good way.
When the material in each unit is handled separately, learners cannot forge robust connections between ideas and build out their mental network of conceptual links—one of the most important tasks in deepening their understanding [@AmbroseEtAl2010; @BiggsCollis1982].
Keeping all the boxes open, even after the units are past, is a harder cognitive task, but it's a better education.

To avoid siloing, two methods that teachers can use are interleaving material and what Laura calls Velcro teaching.


### Interleaving

Rather than focusing only on one topic, discussing it exhaustively, and then moving on to the next one without referring back to earlier ideas, by interleaving, we switch back and forth between topics.

So, unlike a silo structure such as

- Day 1: Topic A
- Day 2: Topic A
- Day 3: Topic B
- Day 4: Topic B,

an interleaved structure might be

- Day 1: Topic A
- Day 2: Topic B
- Day 3: Topic A
- Day 4: Topic B.

Returning to Topic A after Topic B has been opened invites learners to draw connections between A and B that they may otherwise have missed.

Interleaving has been shown to strengthen learning and aid retention [@BrownEtAl2014].
It's cognitively harder work for both student and teacher, but it improves learning long-term.


### Velcro teaching

Velcro teaching is Laura's term for the process of explicitly drawing connections between material in different sections of a course.
You can set the hook forward ("Next week, we'll learn about Y and see how it connects to X") and then deliver on that hook ("Remember X from last week? Here's Y, and now we're going to learn how X and Y connect.").
We've been setting hooks in this text, too, for example back in [Section @sec-learning-taxonomies], when we mentioned all the places the SOLO taxonomy will reappear.

Hooks aren't always helpful, though.
Sometimes setting a hook forward can be dissatisfying, especially when students have no frame of reference for what the topic will be: foreshadowing that "we'll hear more about [confusing unfamiliar jargon] later" can frustrate students in a way similar to "you'll understand when you're older".
So use your judgement about when providing information up front would offer helpful structure (see below) and when it might just confuse things further.

The practice of drawing connections between older and newer ideas—that is, the practice of Velcro teaching—requires you to

- know your material at least a week ahead of time, so that you can set hooks forward, and
- understand the range of ways in which the topics in your course can be linked together.

The first couple times through a course, this level of understanding can be hard to reach.
So give yourself grace—early on, making it through the week is enough.
Even if it's not every session, any hook that is set and delivered on can help students forge important connections between ideas.
And any time that you can ask students to bring earlier ideas into a new context will challenge them but, ultimately, strengthen their learning.


## Transparency about structure

However you choose to structure your course, tell students as early as possible what they should expect.
Telling people what's coming before they experience it is called "pre-organising".
Novice learners and the average person function well in a pre-organised environment.
So being transparent about what you have planned and how it should all fit together *in advance* can help get students on board.

The alternative to pre-organising is post-organising: giving people an experience and then helping them put a structure over it in retrospect.
Post-organising is better-suited for more masterful learners, people who are more comfortable juggling several live ideas at once.

Transparency about structure also applies at the level of individual lessons.
At the beginning of a lesson, give students an outline of what they can expect from that session.
And importantly, check off topics from the outline as they're accomplished.
The goal is for everybody to be able to tell where they are in the day's schedule, even if (when) their attention falters.
People should always be able to find a way back in.

---

In the last several sections, we have been focusing on the cognitive process of learning and how we as educators can facilitate it.

In [Section @sec-more-than-grades], we pivot to the behavioural outcomes of learning and how we can assess them.
