# Defining learning {#sec-defining-learning}

Learning is a process, a change in cognition.
As educators, we try to facilitate this cognitive process (our focus in [Part 2](../part2/learning-is-messy.qmd) of this book).
But we can't see into learners' minds to know what has actually changed.
All we can access is what learners *do* with what they've learned.
Based on their behaviour, we make inferences about their learning (our focus in [Part 3](../part3/more-than-grades.qmd) of this book).

In very broad terms, learning can be defined as the process of building a consistent response to a stimulus.
You know you've learned when you respond to a stimulus in a new and consistent way.
And different levels of learners may show different kinds of consistent responses.

- **A novice learner** will have a memorised response to a stimulus.
This response is consistent, but it's not nuanced nor connected to other ideas.
When faced with a new context, the novice learner might say something like, "You've not taught me how to answer this," or "I don't know where to begin."

- **An intermediate learner** knows that there are nuances behind an idea and connections to be made, but might not be able to convey them precisely.
When faced with a new context, the intermediate learner might give responses at a simpler level of cognition than what the new context demands (we'll talk more about levels of cognition next, in [Section @sec-learning-taxonomies]), or they might say something like, "I've memorised everything, but I still don't understand!"

- **A master learner** knows the nuances and connections and chooses the response that's most appropriate in each situation.
When faced with a new context, a master learner recognises what parts of their understanding are transferrable and is able to situate them in the new scenario.

Even though these responses all reflect different degrees or levels of cognition, they all still reflect learning.
Next we'll discuss two common ways of conceptualising these different levels of cognition: Bloom's taxonomy and the SOLO taxonomy.